services:
  - type: web
    name: careercraft
    env: node
    region: singapore  # Choose the region closest to your users
    buildCommand: |
      cd Frontend && npm install && npm run build && \
      cd ../Backend && npm install
    startCommand: cd Backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: GEMINI_API_KEY
        sync: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html